<?php

use Illuminate\Database\Seeder;
use Xditn\Base\modules\Common\Support\ImportPermissions;

return new class extends Seeder
{
    /**
     * Run the seeder.
     */
    public function run(): void
    {
        $menus = $this->menus();

        ImportPermissions::import($menus);
    }

    public function menus(): array
    {
        return [
            0 => [
                'id' => 501,
                'parent_id' => 0,
                'permission_name' => 'openapi',
                'route' => '/openapi',
                'icon' => '',
                'module' => 'openapi',
                'permission_mark' => '',
                'component' => '/layout/index.vue',
                'redirect' => null,
                'keepalive' => 1,
                'type' => 1,
                'hidden' => 1,
                'sort' => 1,
                'active_menu' => '',
                'creator_id' => 1,
                'created_at' => '2024-10-19 09:45',
                'updated_at' => '2024-10-19 09:45',
                'children' => [
                    0 => [
                        'id' => 508,
                        'parent_id' => 501,
                        'permission_name' => '请求日志',
                        'route' => 'openapiRequestLog',
                        'icon' => '',
                        'module' => 'openapi',
                        'permission_mark' => 'openapiRequestLog',
                        'component' => '/openapi/openapiRequestLog/index.vue',
                        'redirect' => null,
                        'keepalive' => 1,
                        'type' => 2,
                        'hidden' => 1,
                        'sort' => 1,
                        'active_menu' => '',
                        'creator_id' => 1,
                        'created_at' => '2024-10-20 16:19',
                        'updated_at' => '2024-10-20 16:19',
                        'children' => [
                            0 => [
                                'id' => 510,
                                'parent_id' => 508,
                                'permission_name' => '删除',
                                'route' => '',
                                'icon' => '',
                                'module' => 'openapi',
                                'permission_mark' => 'openapiRequestLog@destroy',
                                'component' => '',
                                'redirect' => '',
                                'keepalive' => 1,
                                'type' => 3,
                                'hidden' => 1,
                                'sort' => 2,
                                'active_menu' => '',
                                'creator_id' => 1,
                                'created_at' => '2024-10-20 16:19',
                                'updated_at' => '2024-10-20 16:19',
                            ],
                            1 => [
                                'id' => 509,
                                'parent_id' => 508,
                                'permission_name' => '列表',
                                'route' => '',
                                'icon' => '',
                                'module' => 'openapi',
                                'permission_mark' => 'openapiRequestLog@index',
                                'component' => '',
                                'redirect' => '',
                                'keepalive' => 1,
                                'type' => 3,
                                'hidden' => 1,
                                'sort' => 1,
                                'active_menu' => '',
                                'creator_id' => 1,
                                'created_at' => '2024-10-20 16:19',
                                'updated_at' => '2024-10-20 16:19',
                            ],
                        ],
                    ],
                    1 => [
                        'id' => 502,
                        'parent_id' => 501,
                        'permission_name' => '用户管理',
                        'route' => 'users',
                        'icon' => '',
                        'module' => 'openapi',
                        'permission_mark' => 'users',
                        'component' => '/openapi/users/index.vue',
                        'redirect' => null,
                        'keepalive' => 1,
                        'type' => 2,
                        'hidden' => 1,
                        'sort' => 1,
                        'active_menu' => '',
                        'creator_id' => 1,
                        'created_at' => '2024-10-19 09:45',
                        'updated_at' => '2024-10-19 09:45',
                        'children' => [
                            0 => [
                                'id' => 512,
                                'parent_id' => 502,
                                'permission_name' => '余额重置',
                                'route' => '',
                                'icon' => '',
                                'module' => 'openapi',
                                'permission_mark' => 'users@charge',
                                'component' => '',
                                'redirect' => '',
                                'keepalive' => 1,
                                'type' => 3,
                                'hidden' => 1,
                                'sort' => 1,
                                'active_menu' => '',
                                'creator_id' => 1,
                                'created_at' => '1970-01-01 08:00',
                                'updated_at' => '1970-01-01 08:00',
                            ],
                            1 => [
                                'id' => 507,
                                'parent_id' => 502,
                                'permission_name' => '删除',
                                'route' => '',
                                'icon' => '',
                                'module' => 'openapi',
                                'permission_mark' => 'users@destroy',
                                'component' => '',
                                'redirect' => '',
                                'keepalive' => 1,
                                'type' => 3,
                                'hidden' => 1,
                                'sort' => 5,
                                'active_menu' => '',
                                'creator_id' => 1,
                                'created_at' => '2024-10-19 09:45',
                                'updated_at' => '2024-10-19 09:45',
                            ],
                            2 => [
                                'id' => 503,
                                'parent_id' => 502,
                                'permission_name' => '列表',
                                'route' => '',
                                'icon' => '',
                                'module' => 'openapi',
                                'permission_mark' => 'users@index',
                                'component' => '',
                                'redirect' => '',
                                'keepalive' => 1,
                                'type' => 3,
                                'hidden' => 1,
                                'sort' => 1,
                                'active_menu' => '',
                                'creator_id' => 1,
                                'created_at' => '2024-10-19 09:45',
                                'updated_at' => '2024-10-19 09:45',
                            ],
                            3 => [
                                'id' => 511,
                                'parent_id' => 502,
                                'permission_name' => '重置密钥',
                                'route' => '',
                                'icon' => '',
                                'module' => 'openapi',
                                'permission_mark' => 'users@regenerate',
                                'component' => '',
                                'redirect' => '',
                                'keepalive' => 1,
                                'type' => 3,
                                'hidden' => 1,
                                'sort' => 1,
                                'active_menu' => '',
                                'creator_id' => 1,
                                'created_at' => '1970-01-01 08:00',
                                'updated_at' => '1970-01-01 08:00',
                            ],
                            4 => [
                                'id' => 505,
                                'parent_id' => 502,
                                'permission_name' => '读取',
                                'route' => '',
                                'icon' => '',
                                'module' => 'openapi',
                                'permission_mark' => 'users@show',
                                'component' => '',
                                'redirect' => '',
                                'keepalive' => 1,
                                'type' => 3,
                                'hidden' => 1,
                                'sort' => 3,
                                'active_menu' => '',
                                'creator_id' => 1,
                                'created_at' => '2024-10-19 09:45',
                                'updated_at' => '2024-10-19 09:45',
                            ],
                            5 => [
                                'id' => 504,
                                'parent_id' => 502,
                                'permission_name' => '新增',
                                'route' => '',
                                'icon' => '',
                                'module' => 'openapi',
                                'permission_mark' => 'users@store',
                                'component' => '',
                                'redirect' => '',
                                'keepalive' => 1,
                                'type' => 3,
                                'hidden' => 1,
                                'sort' => 2,
                                'active_menu' => '',
                                'creator_id' => 1,
                                'created_at' => '2024-10-19 09:45',
                                'updated_at' => '2024-10-19 09:45',
                            ],
                            6 => [
                                'id' => 506,
                                'parent_id' => 502,
                                'permission_name' => '更新',
                                'route' => '',
                                'icon' => '',
                                'module' => 'openapi',
                                'permission_mark' => 'users@update',
                                'component' => '',
                                'redirect' => '',
                                'keepalive' => 1,
                                'type' => 3,
                                'hidden' => 1,
                                'sort' => 4,
                                'active_menu' => '',
                                'creator_id' => 1,
                                'created_at' => '2024-10-19 09:45',
                                'updated_at' => '2024-10-19 09:45',
                            ],
                        ],
                    ],
                ],
            ],
        ];
    }
};
